/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, clang++ 17.0.0 -fPIC -O3) */

module seq_detector_0011(clk, reset, data_in, detected);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input data_in;
  wire data_in;
  output detected;
  wire detected;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [2:0] history;
  INV_X1 _11_ (
    .A(reset),
    .ZN(_05_)
  );
  AND2_X1 _12_ (
    .A1(_05_),
    .A2(history[0]),
    .ZN(_01_)
  );
  AND2_X1 _13_ (
    .A1(_05_),
    .A2(data_in),
    .ZN(_02_)
  );
  INV_X1 _14_ (
    .A(history[2]),
    .ZN(_06_)
  );
  NOR2_X1 _15_ (
    .A1(_00_),
    .A2(history[1]),
    .ZN(_07_)
  );
  AND4_X1 _16_ (
    .A1(_06_),
    .A2(_07_),
    .A3(_05_),
    .A4(data_in),
    .ZN(_03_)
  );
  AND2_X1 _17_ (
    .A1(_05_),
    .A2(history[1]),
    .ZN(_04_)
  );
  DFF_X1 _18_ (
    .CK(clk),
    .D(_03_),
    .Q(detected),
    .QN(_09_)
  );
  DFF_X1 _19_ (
    .CK(clk),
    .D(_02_),
    .Q(history[0]),
    .QN(_00_)
  );
  DFF_X1 _20_ (
    .CK(clk),
    .D(_01_),
    .Q(history[1]),
    .QN(_10_)
  );
  DFF_X1 _21_ (
    .CK(clk),
    .D(_04_),
    .Q(history[2]),
    .QN(_08_)
  );
endmodule
