/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, clang++ 17.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "outputs/seq_detector_0011.sv:1.1-24.10" *)
module seq_detector_0011(clk, reset, data_in, detected);
  (* src = "outputs/seq_detector_0011.sv:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "outputs/seq_detector_0011.sv:3.11-3.16" *)
  input reset;
  wire reset;
  (* src = "outputs/seq_detector_0011.sv:4.11-4.18" *)
  input data_in;
  wire data_in;
  (* src = "outputs/seq_detector_0011.sv:5.16-5.24" *)
  output detected;
  reg detected = 1'h0;
  (* src = "outputs/seq_detector_0011.sv:19.25-19.55" *)
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "outputs/seq_detector_0011.sv:8.15-8.22" *)
  reg [2:0] history = 3'h0;
  assign _1_ = history[0] & ~(history[1]);
  assign _2_ = data_in & ~(history[2]);
  assign _0_ = _1_ & _2_;
  (* src = "outputs/seq_detector_0011.sv:14.5-22.8" *)
  always @(posedge clk)
    if (reset) history[0] <= 1'h0;
    else history[0] <= data_in;
  (* src = "outputs/seq_detector_0011.sv:14.5-22.8" *)
  always @(posedge clk)
    if (reset) history[1] <= 1'h0;
    else history[1] <= history[0];
  (* src = "outputs/seq_detector_0011.sv:14.5-22.8" *)
  always @(posedge clk)
    if (reset) history[2] <= 1'h0;
    else history[2] <= history[1];
  (* src = "outputs/seq_detector_0011.sv:14.5-22.8" *)
  always @(posedge clk)
    if (reset) detected <= 1'h0;
    else detected <= _0_;
endmodule
