/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, clang++ 17.0.0 -fPIC -O3) */

module seq_detector_0011(clk, reset, data_in, detected);
  input clk;
  input reset;
  input data_in;
  output detected;
  reg detected;
  wire _0_;
  wire _1_;
  wire _2_;
  reg [2:0] history;

  assign _1_ = history[0] & ~(history[1]);
  assign _2_ = data_in & ~(history[2]);
  assign _0_ = _1_ & _2_;

  always @(posedge clk)
    if (reset) history[0] <= 1'h0;
    else history[0] <= data_in;

  always @(posedge clk)
    if (reset) history[1] <= 1'h0;
    else history[1] <= history[0];

  always @(posedge clk)
    if (reset) history[2] <= 1'h0;
    else history[2] <= history[1];

  always @(posedge clk)
    if (reset) detected <= 1'h0;
    else detected <= _0_;

endmodule
